<?php
session_start();
require_once "../connect.php";

$ids = '('.$_REQUEST['ids'].')';

$dt_start = $_SESSION['start'];
$dt_end = $_SESSION['end'];


$xmlString = '<ENVELOPE>
 <HEADER>
  <TALLYREQUEST>Import Data</TALLYREQUEST>
 </HEADER>
 <BODY>
  <IMPORTDATA>
   <REQUESTDESC>
    <REPORTNAME>Vouchers</REPORTNAME>
    <STATICVARIABLES>
     <SVCURRENTCOMPANY>AMMAR INDUSTRIAL CORPORATION</SVCURRENTCOMPANY>
    </STATICVARIABLES>
   </REQUESTDESC>
   <REQUESTDATA>';
 
if($_REQUEST['ids'] == 'all'){
    $sql = "SELECT * FROM receipts WHERE `date` BETWEEN '$dt_start' AND '$dt_end' ORDER BY `date`";
}else{
    $sql = "SELECT * FROM receipts WHERE id IN $ids";
}
$query = $db->query($sql);

while($row = $query->fetch_assoc()){

    $invoice = $row['si_no'];
    $client = $row['client'];
    $client = htmlspecialchars($client, ENT_XML1, 'UTF-8');
    $amount = $row['amount'];
    $date = date('Ymd', strtotime($row['date']));

    // Testing
    // $date = '20200401';

    $account = $row['account'];
    $mode = $row['mode'];
    $instrument = $row['instrument'];
    $bank = $row['bank_name'];
    $bank = htmlspecialchars($bank, ENT_XML1, 'UTF-8');
    $insdate = date('Ymd', strtotime($row['ins_date']));

    $sales_invoice = json_decode($row['sales_invoice'],true);
    $len = sizeof($sales_invoice['si_no']);

    $xmlString .= '<TALLYMESSAGE xmlns:UDF="TallyUDF">
    <VOUCHER VCHTYPE="Receipt" ACTION="Create" OBJVIEW="Accounting Voucher View">
        <OLDAUDITENTRYIDS.LIST TYPE="Number">
            <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
        </OLDAUDITENTRYIDS.LIST>
        <DATE>'.$date.'</DATE>
        <GUID>fb0a08e7-3fca-4e96-8926-f090dfb9c8ae-00000287</GUID>
        <VOUCHERTYPENAME>Receipt</VOUCHERTYPENAME>
        <PARTYLEDGERNAME>'.$client.'</PARTYLEDGERNAME>
        <CSTFORMISSUETYPE />
        <CSTFORMRECVTYPE />
        <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
        <PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW>
        <VCHGSTCLASS />
        <DIFFACTUALQTY>No</DIFFACTUALQTY>
        <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
        <ASORIGINAL>No</ASORIGINAL>
        <AUDITED>No</AUDITED>
        <FORJOBCOSTING>No</FORJOBCOSTING>
        <ISOPTIONAL>No</ISOPTIONAL>
        <USEFOREXCISE>No</USEFOREXCISE>
        <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
        <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
        <USEFORINTEREST>No</USEFORINTEREST>
        <USEFORGAINLOSS>No</USEFORGAINLOSS>
        <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
        <USEFORCOMPOUND>No</USEFORCOMPOUND>
        <USEFORSERVICETAX>No</USEFORSERVICETAX>
        <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
        <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
        <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
        <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
        <EXCISEOPENING>No</EXCISEOPENING>
        <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
        <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
        <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
        <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
        <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
        <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
        <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
        <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
        <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
        <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
        <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
        <ISISDVOUCHER>No</ISISDVOUCHER>
        <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
        <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
        <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
        <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
        <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
        <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
        <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
        <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
        <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
        <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
        <ISCANCELLED>No</ISCANCELLED>
        <HASCASHFLOW>Yes</HASCASHFLOW>
        <ISPOSTDATED>No</ISPOSTDATED>
        <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
        <ISINVOICE>No</ISINVOICE>
        <MFGJOURNAL>No</MFGJOURNAL>
        <HASDISCOUNTS>No</HASDISCOUNTS>
        <ASPAYSLIP>No</ASPAYSLIP>
        <ISCOSTCENTRE>No</ISCOSTCENTRE>
        <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
        <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
        <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
        <ISVOID>No</ISVOID>
        <ISONHOLD>No</ISONHOLD>
        <ORDERLINESTATUS>No</ORDERLINESTATUS>
        <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
        <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
        <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
        <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
        <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
        <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
        <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
        <ISDELETED>No</ISDELETED>
        <CHANGEVCHMODE>No</CHANGEVCHMODE>
        <EXCLUDEDTAXATIONS.LIST> </EXCLUDEDTAXATIONS.LIST>
        <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
        <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
        <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
        <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
        <SUPPLEMENTARYDUTYHEADDETAILS.LIST> </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
        <EWAYBILLDETAILS.LIST> </EWAYBILLDETAILS.LIST>
        <INVOICEDELNOTES.LIST> </INVOICEDELNOTES.LIST>
        <INVOICEORDERLIST.LIST> </INVOICEORDERLIST.LIST>
        <INVOICEINDENTLIST.LIST> </INVOICEINDENTLIST.LIST>
        <ATTENDANCEENTRIES.LIST> </ATTENDANCEENTRIES.LIST>
        <ORIGINVOICEDETAILS.LIST> </ORIGINVOICEDETAILS.LIST>
        <INVOICEEXPORTLIST.LIST> </INVOICEEXPORTLIST.LIST>
        <ALLLEDGERENTRIES.LIST>
            <OLDAUDITENTRYIDS.LIST TYPE="Number">
                <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
            </OLDAUDITENTRYIDS.LIST>
            <LEDGERNAME>'.$client.'</LEDGERNAME>
            <GSTCLASS />
            <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
            <LEDGERFROMITEM>No</LEDGERFROMITEM>
            <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
            <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
            <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
            <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
            <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
            <AMOUNT>'.$amount.'.00</AMOUNT>
            <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
            <BANKALLOCATIONS.LIST> </BANKALLOCATIONS.LIST>';
            for($i=0;$i<$len;$i++){
                $xmlString .= '<BILLALLOCATIONS.LIST>
                    <NAME>'.$sales_invoice['si_no'][$i].'</NAME>
                    <BILLTYPE>New Ref</BILLTYPE>
                    <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
                    <AMOUNT>'.$sales_invoice['amount'][$i].'</AMOUNT>
                    <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
                    <STBILLCATEGORIES.LIST> </STBILLCATEGORIES.LIST>
                </BILLALLOCATIONS.LIST>';
            }
            $xmlString .= '<INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
            <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
            <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
            <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
            <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
            <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
            <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
            <RATEDETAILS.LIST> </RATEDETAILS.LIST>
            <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
            <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
            <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
            <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
            <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
            <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
            <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
            <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
            <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
            <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
            <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
            <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
        </ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST>
            <OLDAUDITENTRYIDS.LIST TYPE="Number">
                <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
            </OLDAUDITENTRYIDS.LIST>
            <LEDGERNAME>'.$account.'</LEDGERNAME>
            <GSTCLASS />
            <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
            <LEDGERFROMITEM>No</LEDGERFROMITEM>
            <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
            <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
            <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
            <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
            <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
            <AMOUNT>-'.$amount.'.00</AMOUNT>
            <SERVICETAXDETAILS.LIST> </SERVICETAXDETAILS.LIST>
            <BANKALLOCATIONS.LIST>
                <DATE>'.$date.'</DATE>
                <INSTRUMENTDATE>'.$insdate.'</INSTRUMENTDATE>
                <NAME>39f49c29-7374-4ca6-a2a0-99aec38cfb3d</NAME>
                <TRANSACTIONTYPE>'.$mode.'</TRANSACTIONTYPE>
                <BANKNAME>'.$bank.'</BANKNAME>
                <PAYMENTFAVOURING>'.$client.'</PAYMENTFAVOURING>
                <INSTRUMENTNUMBER>'.$instrument.'</INSTRUMENTNUMBER>
                <UNIQUEREFERENCENUMBER>4zitgHwboqzte2Bc</UNIQUEREFERENCENUMBER>
                <STATUS>No</STATUS>
                <PAYMENTMODE>Transacted</PAYMENTMODE>
                <BANKPARTYNAME>'.$client.'</BANKPARTYNAME>
                <ISCONNECTEDPAYMENT>No</ISCONNECTEDPAYMENT>
                <ISSPLIT>No</ISSPLIT>
                <ISCONTRACTUSED>No</ISCONTRACTUSED>
                <ISACCEPTEDWITHWARNING>No</ISACCEPTEDWITHWARNING>
                <ISTRANSFORCED>No</ISTRANSFORCED>
                <CHEQUEPRINTED> 1</CHEQUEPRINTED>
                <AMOUNT>-'.$amount.'.00</AMOUNT>
                <CONTRACTDETAILS.LIST> </CONTRACTDETAILS.LIST>
                <BANKSTATUSINFO.LIST> </BANKSTATUSINFO.LIST>
            </BANKALLOCATIONS.LIST>
            <BILLALLOCATIONS.LIST> </BILLALLOCATIONS.LIST>
            <INTERESTCOLLECTION.LIST> </INTERESTCOLLECTION.LIST>
            <OLDAUDITENTRIES.LIST> </OLDAUDITENTRIES.LIST>
            <ACCOUNTAUDITENTRIES.LIST> </ACCOUNTAUDITENTRIES.LIST>
            <AUDITENTRIES.LIST> </AUDITENTRIES.LIST>
            <INPUTCRALLOCS.LIST> </INPUTCRALLOCS.LIST>
            <DUTYHEADDETAILS.LIST> </DUTYHEADDETAILS.LIST>
            <EXCISEDUTYHEADDETAILS.LIST> </EXCISEDUTYHEADDETAILS.LIST>
            <RATEDETAILS.LIST> </RATEDETAILS.LIST>
            <SUMMARYALLOCS.LIST> </SUMMARYALLOCS.LIST>
            <STPYMTDETAILS.LIST> </STPYMTDETAILS.LIST>
            <EXCISEPAYMENTALLOCATIONS.LIST> </EXCISEPAYMENTALLOCATIONS.LIST>
            <TAXBILLALLOCATIONS.LIST> </TAXBILLALLOCATIONS.LIST>
            <TAXOBJECTALLOCATIONS.LIST> </TAXOBJECTALLOCATIONS.LIST>
            <TDSEXPENSEALLOCATIONS.LIST> </TDSEXPENSEALLOCATIONS.LIST>
            <VATSTATUTORYDETAILS.LIST> </VATSTATUTORYDETAILS.LIST>
            <COSTTRACKALLOCATIONS.LIST> </COSTTRACKALLOCATIONS.LIST>
            <REFVOUCHERDETAILS.LIST> </REFVOUCHERDETAILS.LIST>
            <INVOICEWISEDETAILS.LIST> </INVOICEWISEDETAILS.LIST>
            <VATITCDETAILS.LIST> </VATITCDETAILS.LIST>
            <ADVANCETAXDETAILS.LIST> </ADVANCETAXDETAILS.LIST>
        </ALLLEDGERENTRIES.LIST>
        <PAYROLLMODEOFPAYMENT.LIST> </PAYROLLMODEOFPAYMENT.LIST>
        <ATTDRECORDS.LIST> </ATTDRECORDS.LIST>
        <GSTEWAYCONSIGNORADDRESS.LIST> </GSTEWAYCONSIGNORADDRESS.LIST>
        <GSTEWAYCONSIGNEEADDRESS.LIST> </GSTEWAYCONSIGNEEADDRESS.LIST>
        <TEMPGSTRATEDETAILS.LIST> </TEMPGSTRATEDETAILS.LIST>';        

    $xmlString .= '</VOUCHER>
</TALLYMESSAGE>';

}


  $xmlString .= '</REQUESTDATA>
  </IMPORTDATA>
 </BODY>
</ENVELOPE>';

$dom = new DOMDocument;
$dom->preserveWhiteSpace = TRUE;
$dom->loadXML($xmlString);

//Save XML as a file
$dom->save('receipt.xml');

//View XML document
$dom->formatOutput = TRUE;
echo $dom->saveXml();

?>